import * as React from 'react';
import Head from 'next/head';

function Lighter() {
  return (
    <div className="min-h-screen bg-background text-primary-foreground p-8 flex flex-col items-center justify-center">
      <Head>
        <title>Default Next.js Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <h1 className="text-4xl font-bold">
          Welcome to <a href="https://nextjs.org" className="text-primary">Next.js</a>!
        </h1>

        <p className="mt-4 text-lg">
          Get started by editing{' '}
          <code className="bg-muted p-1 rounded">pages/index.js</code>
        </p>

        <div className="mt-8">
          <button
            onClick={() => alert('Hello, Next.js!')}
            className="px-4 py-2 bg-accent text-background font-bold rounded"
          >
            Click Me PLease
          </button>
        </div>
      </main>

      <footer className="mt-8">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="text-secondary"
        >
          Powered by{' '}
          <span className="font-bold">Vercel</span>
        </a>
      </footer>
    </div>
  );
}

export default Lighter
